require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'CleanAnimals' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])


  target 'CleanAnimalsTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.

  post_install do |pi|
    pi.pods_project.targets.each do |t|
      t.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '10.0'
      end
    end
  end

end

target 'CleanAnimals-tvOS' do
  # Pods for CleanAnimals-tvOS

  target 'CleanAnimals-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
