name: On Push CI
on:
  push:
    branches:
      - '*CI'
      - '!master'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v2


      - name: Install Bundle for Fastlane
        run: gem install fastlane -NV

      - name: Install npm dependencies
        run: |
          npm ci

      - name: Run unit and integration tests
        run: |
          npm run ci:test

      - name: Set Github Actions Bot Email
        run: git config --local user.email "action@github.com"

      - name: Set Github Actions Bot Name
        run: git config --local user.name "GitHub Action"


      - name: Bump version (STAGING-PATCH)
        run: npm run bump-patch

      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Build with Gradle
        id: build
        run:  cd android && ./gradlew build

      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          name: app-release.apk
          path: android/app/build/outputs/apk/release/

      - name: Build Release AAB
        id: buildRelease
        run: cd android && ./gradlew bundleRelease

      - name: Sign AAB
        id: sign
        uses: r0adkll/sign-android-release@v1
        with:
          releaseDirectory: android/app/build/outputs/bundle/release
          signingKeyBase64: ${{ secrets.SIGNING_KEY }}
          alias: ${{ secrets.ALIAS }}
          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}

      - name: Upload AAB
        id: uploadArtifact
        uses: actions/upload-artifact@v1
        with:
            name: app
            path: android/app/build/outputs/bundle/release/app-release.aab

      - name: Code Push
        run: npm run codepush:staging


