name: On Push CI
on:
  push:
    branches:
      - '*CI'
      - '!master'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install npm dependencies
        run: |
          npm ci

      - name: Run unit and integration tests
        run: |
          npm run ci:test

      - name: gitconfig Email
        run:
          git config --global user.email "ci@github.com"

      - name: gitconfig Username
        run:
          git config --global user.name "Continuous Integration"

      - name: Bump PATCH JSON
        run: |
          npm version patch

      - name: Setup Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: '>= 2.6'

      - name: Install bundle
        run: |
          sudo apt-get -yqq install libpq-dev
          gem install bundler
          bundle install --jobs 4 --retry 3

      - name: Bump PATCH Fastlane
        uses: maierj/fastlane-action@v2.0.0
        with:
          lane: 'bundle exec bump'

      - name: Commit changes
        uses: EndBug/add-and-commit@v7
        with:
          author_name: Continuous Integration
          author_email: ci@github.com
          message: 'bumping version'
          add: '.'

      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Build with Gradle
        id: build
        run:  cd android && ./gradlew build

      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          name: app-release.apk
          path: android/app/build/outputs/apk/release/

      - name: Build Release AAB
        id: buildRelease
        run: cd android && ./gradlew bundleRelease

      - name: Sign AAB
        id: sign
        uses: r0adkll/sign-android-release@v1
        with:
          releaseDirectory: android/app/build/outputs/bundle/release
          signingKeyBase64: ${{ secrets.SIGNING_KEY }}
          alias: ${{ secrets.ALIAS }}
          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}

      - name: Upload AAB
        id: uploadArtifact
        uses: actions/upload-artifact@v1
        with:
            name: app
            path: android/app/build/outputs/bundle/release/app-release.aab



