name: On Push CI
on:
  push:
    branches:
      - '*CI'
      - '!master'

jobs:
  pre-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install npm dependencies
        run: |
          npm ci

      - name: Run unit and integration tests
        run: |
          npm run ci:test

  code-push:
    needs: pre-build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Check out code
        uses: actions/checkout@master
        with:
          fetch-depth: '0'

      - name: Bump version and push tag
        uses: ChloePlanet/github-tag-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GB_TOKEN }}
          WITH_V: true

      - name: Set Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: '>= 2.6'

      - name: Codepush Bump
        uses: maierj/fastlane-action@v2.0.0
        with:
          lane: 'bump'

      - name: Commit changes
        uses: EndBug/add-and-commit@v7
        with:
          author_name: Daniel Kiesshau
          author_email: danielkiesshau@outlook.com
          message: 'bumping ersion'
          add: '.'

      - name: Deploy to Codepush (STAGING)
        uses: NishanthShankar/codepush-action@master
        with:
          args:  release-react -a danielkiesshau/CleanAnimals -d Staging -t *
        env:
          APPCENTER_ACCESS_TOKEN: ${{ secrets.CI_API_KEY }}

  build:
    needs: [pre-build, code-push]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Build with Gradle
        id: build
        run:  cd android && ./gradlew build

      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          name: app-release.apk
          path: android/app/build/outputs/apk/release/

      - name: Build Release AAB
        id: buildRelease
        run: cd android && ./gradlew bundleRelease

      - name: Sign AAB
        id: sign
        uses: r0adkll/sign-android-release@v1
        with:
          releaseDirectory: android/app/build/outputs/bundle/release
          signingKeyBase64: ${{ secrets.SIGNING_KEY }}
          alias: ${{ secrets.ALIAS }}
          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}

      - name: Upload AAB
        id: uploadArtifact
        uses: actions/upload-artifact@v1
        with:
            name: app
            path: android/app/build/outputs/bundle/release/app-release.aab



