name: On Push CI
on:
  push:
    branches:
      - '*CI'
      - '!master'

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Npm install
        run: npm ci

      - name: Run unit and integration tests
        run: |
          npm run ci:test
